name: Lamp Deployment

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@main
        # optional:
        with:
          args: "" # args to pass to ansible-lint command